# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Task', max_length=50)),
                ('state', models.IntegerField(default=0)),
                ('rmdir', models.NullBooleanField()),
                ('force', models.NullBooleanField()),
                ('dry_run', models.NullBooleanField()),
                ('restore', models.BooleanField()),
                ('regex', models.BooleanField()),
                ('paths', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='WasteBasket', max_length=50)),
                ('rmdir', models.BooleanField()),
                ('force', models.BooleanField()),
                ('dry_run', models.BooleanField()),
                ('max_size', models.IntegerField(default=32)),
                ('storage_time', models.DurationField(default=datetime.timedelta(30))),
                ('wastebasket_path', models.TextField(default='~/Trash')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='wastebasket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastebasket.WasteBasket'),
        ),
    ]
